export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const GETALLITEM = "GETALLITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
